const fs = require('fs');
const path = require('path');
const express = require('express');
const puppeteer = require('puppeteer');
const PptxGenJS = require('pptxgenjs');

const app = express();
const publicPath = path.join(__dirname, '../public');
app.use(express.static(publicPath));

const port = 5005;
const server = app.listen(port, async () => {
    try {
        console.log("Local server running at http://localhost:" + port);
        const browser = await puppeteer.launch({ headless: "new" });
        const page = await browser.newPage();
        await page.setViewport({ width: 1280, height: 1080 });

        // 1. Screenshot Hero Area (Changes 1 & 2)
        await page.goto(`http://localhost:${port}/`, { waitUntil: 'networkidle0' });
        await new Promise(r => setTimeout(r, 1000));
        await page.screenshot({ path: 'hero_trust.png', clip: { x: 0, y: 150, width: 1280, height: 600 } });

        // 2. Screenshot Technology & Platform Section (Changes 3, 4, 7)
        await page.evaluate(() => {
            const el = document.getElementById('technology-platform');
            if(el) el.scrollIntoView({ behavior: 'instant', block: 'center' });
        });
        await new Promise(r => setTimeout(r, 1000));
        await page.screenshot({ path: 'tech_platform.png', clip: { x: 0, y: 300, width: 1280, height: 600 } });

        // 3. Screenshot Footer Credibility Strip (Change 5)
        await page.evaluate(() => {
            const el = document.querySelector('footer');
            if(el) el.scrollIntoView({ behavior: 'instant', block: 'end' });
        });
        await new Promise(r => setTimeout(r, 1000));
        await page.screenshot({ path: 'footer_strip.png', clip: { x: 0, y: 780, width: 1280, height: 300 } });

        // 4. Screenshot About/Trust Section (Change 6)
        await page.evaluate(() => {
            window.scrollTo({ top: 0, behavior: 'instant' });
            if (typeof openAboutUs === 'function') openAboutUs();
        });
        await new Promise(r => setTimeout(r, 1500));
        await page.screenshot({ path: 'about_modal.png', clip: { x: 200, y: 100, width: 880, height: 800 } });

        await browser.close();
        console.log("Screenshots generated for PowerPoint.");

        // Build Presentation
        let pptx = new PptxGenJS();
        pptx.layout = 'LAYOUT_16x9';

        // Slide 1: Title
        let slide1 = pptx.addSlide();
        slide1.background = { color: '1E3A8A' }; // Navy
        slide1.addText("Implementation Validation Report", { x: 1, y: 2, w: '80%', color: 'FFFFFF', fontSize: 36, bold: true });
        slide1.addText("NVIDIA Inception & RadiantLogiq Integration", { x: 1, y: 3, w: '80%', color: 'E2E8F0', fontSize: 24 });
        slide1.addText("Generated by: Implementation Analytics Team", { x: 1, y: 5.5, w: '80%', color: 'CBD5E1', fontSize: 14 });

        // Slide 2: Hero Section
        let slide2 = pptx.addSlide();
        slide2.addText("1. Homepage Hero & Trust Line", { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '1E3A8A' });
        slide2.addText("Changes: Added 'Powered by RadiantLogiq' and platform trust copy under the hero.", { x: 0.5, y: 1.1, w: '90%', fontSize: 14, color: '475569' });
        slide2.addImage({ path: 'hero_trust.png', x: 1, y: 2, w: 8, h: 3.75 });

        // Slide 3: Technology Section
        let slide3 = pptx.addSlide();
        slide3.addText("2. Technology & Platform Block", { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '1E3A8A' });
        slide3.addText("Changes: Inserted DoseSpot trust line and RadiantLogiq provider micro-copy.", { x: 0.5, y: 1.1, w: '90%', fontSize: 14, color: '475569' });
        slide3.addImage({ path: 'tech_platform.png', x: 1, y: 2, w: 8, h: 3.75 });

        // Slide 4: Footer Strip
        let slide4 = pptx.addSlide();
        slide4.addText("3. Footer NVIDIA Credibility Strip", { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '1E3A8A' });
        slide4.addText("Changes: Added NVIDIA Inception badge and exact copyright trademark string.", { x: 0.5, y: 1.1, w: '90%', fontSize: 14, color: '475569' });
        slide4.addImage({ path: 'footer_strip.png', x: 1, y: 2, w: 8, h: 1.8 });

        // Slide 5: About Modal
        let slide5 = pptx.addSlide();
        slide5.addText("4. About Us / Partnership Section", { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '1E3A8A' });
        slide5.addText("Changes: Appended 'physician-led team' statement to the Partnership text.", { x: 0.5, y: 1.1, w: '90%', fontSize: 14, color: '475569' });
        // Scale to fit
        slide5.addImage({ path: 'about_modal.png', x: 2.5, y: 1.5, w: 5, h: 4.5 });

        await pptx.writeFile({ fileName: "C:\\Users\\dayoo\\Downloads\\NVIDIA_Implementation_Validation_Visuals.pptx" });
        console.log("PowerPoint successfully written.");

        // Cleanup
        fs.unlinkSync('hero_trust.png');
        fs.unlinkSync('tech_platform.png');
        fs.unlinkSync('footer_strip.png');
        fs.unlinkSync('about_modal.png');

    } catch (e) {
        console.error("Error generating pptx:", e);
    } finally {
        server.close();
        process.exit(0);
    }
});
