import type { NotificationTopicDefinition } from '../types';
import { asString } from '../format';

export const workspaceTopics = {
  PATIENT_WELCOME: {
    topicKey: 'PATIENT_WELCOME',
    category: 'workspace',
    priority: 'medium',
    allowedChannels: ['email', 'in_app'],
    defaultChannels: ['email', 'in_app'],
    templateKey: 'patient_welcome',
    containsPHI: false,
    requiresAudit: true,
    fromEmail: 'hello@patriotictelehealth.com',
    replyTo: 'hello@patriotictelehealth.com',
    dedupeWindowSeconds: 86_400,
    inboxType: 'account_created',
    buildInboxTitle: () => 'Welcome to Patriotic Telehealth',
    buildInboxBody: () =>
      'Your account is ready. Sign in to complete your next steps.',
    buildHref: () => '/patient',
  },
  STAFF_ACCOUNT_CREATED: {
    topicKey: 'STAFF_ACCOUNT_CREATED',
    category: 'workspace',
    priority: 'medium',
    allowedChannels: ['in_app'],
    defaultChannels: ['in_app'],
    containsPHI: false,
    requiresAudit: true,
    fromEmail: 'hello@patriotictelehealth.com',
    replyTo: 'hello@patriotictelehealth.com',
    dedupeWindowSeconds: 86_400,
    inboxType: 'account_created',
    buildInboxTitle: () => 'Your account is ready',
    buildInboxBody: (data) =>
      `Your ${asString(data.roleLabel, 'team').toLowerCase()} account has been created. Sign in to get started.`,
    buildHref: () => '/login',
  },
  PRIORITY_QUEUE_PAYMENT_SUCCESS_PATIENT: {
    topicKey: 'PRIORITY_QUEUE_PAYMENT_SUCCESS_PATIENT',
    category: 'workspace',
    priority: 'high',
    allowedChannels: ['email', 'in_app'],
    defaultChannels: ['email', 'in_app'],
    templateKey: 'appointment_request_notification',
    containsPHI: false,
    requiresAudit: true,
    fromEmail: 'waitlist@patriotictelehealth.com',
    replyTo: 'waitlist@patriotictelehealth.com',
    dedupeWindowSeconds: 3600,
    inboxType: 'appointment_request',
    buildInboxTitle: () => 'Consultation request received',
    buildInboxBody: (data) =>
      `We received your request for ${asString(data.serviceName, 'your consultation')}. A provider will review it shortly.`,
    buildHref: () => '/patient/appointments',
  },
  PRIORITY_QUEUE_PAYMENT_SUCCESS_PROVIDER: {
    topicKey: 'PRIORITY_QUEUE_PAYMENT_SUCCESS_PROVIDER',
    category: 'practitionerScheduling',
    priority: 'critical',
    allowedChannels: ['email', 'in_app'],
    defaultChannels: ['email', 'in_app'],
    templateKey: 'appointment_request_notification',
    containsPHI: false,
    requiresAudit: true,
    fromEmail: 'waitlist@patriotictelehealth.com',
    replyTo: 'waitlist@patriotictelehealth.com',
    dedupeWindowSeconds: 1800,
    bypassPreferences: true,
    inboxType: 'appointment_request',
    buildInboxTitle: () => 'New consultation request',
    buildInboxBody: (data) =>
      `${asString(data.patientName, 'A patient')} submitted a request for ${asString(data.serviceName, 'a consultation')}.`,
    buildHref: () => '/waitlist',
  },
} satisfies Partial<Record<string, NotificationTopicDefinition>>;
