#!/usr/bin/env bash
set -euo pipefail

cat <<'EOF'
Recommended Cloudflare DNS bootstrap plan:

Staging targets:
- dev.patriotictelehealth.com -> Firebase Hosting site for landing in patriotic-virtual-dev
- emr-dev.patriotictelehealth.com -> Firebase Hosting site for emr in patriotic-virtual-dev

Production targets:
- patriotictelehealth.com -> Firebase Hosting site for landing in patriotic-virtual-prod
- www.patriotictelehealth.com -> redirect to apex or same Firebase Hosting target
- emr.patriotictelehealth.com -> Firebase Hosting site for emr in patriotic-virtual-prod
- api.patriotictelehealth.com -> Cloud Run custom domain mapping for patriotic-virtual-backend

Recommended cutover order:

1. Configure the custom domains in Firebase Hosting first:
   - landing staging
   - emr staging
   - landing production
   - emr production

2. Configure the custom domain mapping in Cloud Run:
   - api.patriotictelehealth.com

3. Copy the exact DNS records generated by Firebase Hosting and Cloud Run into Cloudflare.
   Do not guess these values. Use the records provided by GCP/Firebase.

4. After DNS validation completes, enable proxying if desired.

Suggested Cloudflare record intentions:

- dev.patriotictelehealth.com
  source of truth: Firebase Hosting domain wizard
  likely record type: CNAME or A/AAAA depending on wizard output

- emr-dev.patriotictelehealth.com
  source of truth: Firebase Hosting domain wizard
  likely record type: CNAME or A/AAAA depending on wizard output

- patriotictelehealth.com
  source of truth: Firebase Hosting domain wizard
  likely record type: A/AAAA/TXT verification bundle from Firebase

- www.patriotictelehealth.com
  source of truth: Firebase Hosting domain wizard or Cloudflare redirect rule
  likely record type: CNAME if not handled as a redirect rule

- emr.patriotictelehealth.com
  source of truth: Firebase Hosting domain wizard
  likely record type: CNAME or A/AAAA depending on wizard output

- api.patriotictelehealth.com
  source of truth: Cloud Run domain mapping wizard
  likely record type: CNAME or A/AAAA depending on wizard output

Recommended Cloudflare edge settings after validation:

- SSL/TLS mode: Full (strict)
- Cache bypass for /api/*
- Managed WAF rules enabled
- Conservative or no caching for emr.* until login/session flows are verified

Verification checklist after DNS cutover:

- https://dev.patriotictelehealth.com
- https://emr-dev.patriotictelehealth.com/login
- https://patriotictelehealth.com
- https://emr.patriotictelehealth.com/login
- https://api.patriotictelehealth.com/health

Suggested verification commands after DNS cutover:

- optional Cloudflare API-side check when you have token access:
  If `www.patriotictelehealth.com` is handled by a redirect rule:
  CLOUDFLARE_API_TOKEN=... CLOUDFLARE_ZONE_NAME=patriotictelehealth.com WWW_HANDLING_MODE=redirect npm run verify:cloudflare-zone-setup

  If `www.patriotictelehealth.com` is handled as a real DNS record:
  CLOUDFLARE_API_TOKEN=... CLOUDFLARE_ZONE_NAME=patriotictelehealth.com WWW_HANDLING_MODE=record npm run verify:cloudflare-zone-setup

- DNS resolution from a shell with outbound DNS access:
  npm run verify:dns-resolution

- deployed target smoke checks after staging DNS cutover:
  PUBLIC_URL=https://dev.patriotictelehealth.com EMR_URL=https://emr-dev.patriotictelehealth.com API_URL=https://api.patriotictelehealth.com EXPECT_STAGING_BANNER=1 npm run verify:deployment-targets

- deployed target smoke checks after production DNS cutover:
  PUBLIC_URL=https://patriotictelehealth.com EMR_URL=https://emr.patriotictelehealth.com API_URL=https://api.patriotictelehealth.com EXPECT_STAGING_BANNER=0 npm run verify:deployment-targets

Notes:
- This helper prints the plan only. It does not call Cloudflare or GCP APIs.
- The current session does not have access to the patriotictelehealth.com Cloudflare zone, so exact live records cannot be verified from here.
EOF
